### ISSUE TITLE
New version shown but not downloadable 

### ISSUE THREAD

**Issue by Incedis** [JusticeRage/ApkTrack#103]
ApkTrack Proxy is set up and finds a new version of app. There is no possibility of downloading the new version. It sends me on the net for that specific version. If I change provider, new version is not shown anymore. 
Probably nothing to worry about but could someone explain me if this is expected ?

**Comment by JusticeRage** [comment]
Yes, this is expected.
Here is the workflow for APK searches :
1) If an APK can be located by the app, a download link is provided directly. This is the most desirable case. 
2) Otherwise, a link is provided so the user can look for it online. The search engine can be configured in the settings. 

Finally, when the update source is changed, the last known version is removed because different sources may yield different results.
