### ISSUE TITLE
Subsequent search produce no result

### ISSUE THREAD

**Issue by organik1** [JusticeRage/ApkTrack#130]
#### Expected behavior
After receiving the result of one search, carrying out a subsequent search should be possible.

#### Actual behavior
Subsequent app search produces a blank list.

### How to reproduce
* Launch Apktrack
* Locate the Search icon at the top of the screen
* conduct first search. Input a keyword and hit enter on your keyboard.
* clear keyword, input another keyword and hit enter.

### Testing Environment

* Browser: CHROME
* Operating system: Android v6.0 (marshmallow)
* chipset: spread
* App Version: v2.1.3

#### Recording Of The Bug
![2018_03_30_20_55_19.gif](https://steemitimages.com/DQmSQmecPkYrfNxr8wHgnMw2ZDXUWLM7EdVxUDpZaWc1yJ6/2018_03_30_20_55_19.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@organik/subsequent-search-produce-no-result">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by JusticeRage** [comment]
Hi! Thanks for the report.
I believe this is expected behavior: subsequent searches are performed on the list currently displayed (at least, that's what happens when I try to reproduce the issue). So for instance, if you perform a search for `com.`, a few packages should be displayed, and any subsequent search will only sift through those results.
If you want to start a new search, you need to click the back arrow first.

Can you confirm that this is what happens on your device?

**Comment by organik1** [comment]
Absolutely. That's what happens

**Comment by JusticeRage** [comment]
Okay then. I'll be closing this report as "expected behavior" then. Thanks for taking the time to report it though!

**Comment by organik1** [comment]
I'm glad I could help.
