### ISSUE TITLE
applist sorting

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#39]
On first start of the app after initial installation I got an alphabetically ordered applist.
After the first reloading/rerendering of the applist seems to be really chaotic.
It seems to be ordered the following way:

Update searched and result is "null" combined with never searched, all ordered alphabetical with exceptions (why comes "barcoo" after "UC Browser"?).
After that all outdated apps seem to come alphabetical ordered with exceptions (why comes and the end "Worktime" -> "aLogcat Root" -> "ownCloud" -> "Öffi" ?).
Then all current versions come alphabetically ordered, but here also with an break (after "Yubico Authenticator" the list starts again with  "aCalendar").
Then all apps with no informations found comes alphabetically ordered.
And at the end there is "Google Text-in-Sprache" (Google Text-to-Speech) checked with result null.

It should remain in an consistent order, prefered completely alphabetically order or by option ordered by state.

**Comment by JusticeRage** [comment]
There are separate issues here in my opinion.

> why comes "barcoo" after "UC Browser"

That used to be because the string comparison I used was case sensitive. I have just published a new beta APK which corrects this. I make no promises regarding the ordering of words beginning with "Ö" - let me know how it behaves!

>  And at the end there is "Google Text-in-Sprache" (Google Text-to-Speech) checked with result null.

This is not supposed to happen. Could you please send me a logcat captured during such a request?

> the applist seems to be really chaotic

Apps for which no information is available (new apps that were just installed and/or never checked) are put at the top. Then come the app for which an update is available. After those, the up-to-date apps are displayed. Finally, apps for which the check generated an error (no information found, etc.) are left at the bottom.

Let me know if the latest APK fixes this issue for you!

**Comment by DJaeger** [comment]
> I have just published a new beta APK which corrects this.

Thanks, it works

> I make no promises regarding the ordering of words beginning with "Ö" - let me know how it behaves!

I think it should be handled like O or directly after O.
The same for Ä = A and Ü = U.

> > And at the end there is "Google Text-in-Sprache" (Google Text-to-Speech) checked with result null.
> 
> This is not supposed to happen.

It's not, that it gives an null result (that is because the update was interupted), the curious is, that it is the only app that is listed at the complete end of the list, unregarding the ordering of the other apps and is the only app, that is not within the ordering I described.

> Apps for which no information is available (new apps that were just installed and/or never checked) are put at the top. Then come the app for which an update is available. After those, the up-to-date apps are displayed. Finally, apps for which the check generated an error (no information found, etc.) are left at the bottom.
> 
> Let me know if the latest APK fixes this issue for you!

It looks correct.
Great work.

The only thing I see is, that the updated APKTrack is now listed as first app with "Last check: never".
It seems to be not recognized as the same app.
Could it be, that it is because it is manually installed via APK?

**Comment by JusticeRage** [comment]
Good points (as always, it seems).

> I think it should be handled like O or directly after O.

I take it that accented characters are still pushed to the end of the list. Note to self, [this](http://blog.eyallupu.com/2010/08/four-things-to-remember-about.html) is probably the way to go.

> It's not, that it gives an null result (that is because the update was interupted), the curious is, that it is the only app that is listed at the complete end of the list, unregarding the ordering of the other apps and is the only app, that is not within the ordering I described.

This null thing has its own separate issue (#40). It is caused by a change in the Play Store's layout. ApkTrack considers the "null" response as a fatal error and pushes the app down the list with all the other apps for which it cannot obtain version information.

> The only thing I see is, that the updated APKTrack is now listed as first app with "Last check: never".

This actually happens for every single updated app: the check date and last version information are not carried on. I've just fixed it in my local codebase, so this will not continue in the future versions.

**Comment by DJaeger** [comment]
Within Androids own applist Ö is handled as O, so Öffi is listed after OctoDroid and before OpenDocument.
And this is the position I would search an app with Ö at first.

I don't mean, the case that the Google Text-to-Speed had a state of null, I mean, that it was not where all other app with the same state were.
But now it is not shown anymore.
It shouldn't be seeable, because it is a system-app.

**Comment by JusticeRage** [comment]
I have worked on ApkTrack a bit and I hope to have fixed this accented characters issue. Could you please install this [new APK](kwiatkowski.fr/apktrack/ApkTrack_DJaeger.apk) and let me know if it works? I don't have any "Ö" app to perform tests. If it doesn't work, could you point me to one?

Other fixes for issues you submitted were implemented, feel free to let me know if this solves the problems for you. The full changelog is here: 8ce871f464b1edfc066c1da05d44947f0c5a07ef

**Comment by DJaeger** [comment]
Yes, it is sorted correctly.
Great work.

**Comment by DJaeger** [comment]
I recognized now, that it is not completely correct, as it sorts at first priority by not system app or system app.
With every sorting (by status and by name) it first lists all not system apps by not current, current and not found and then all system apps by not current, current and not found.

**Comment by DJaeger** [comment]
I think I become crazy.
That were systemapps, for example the camera app, that should be hidden.
After choosing show systemapps from menu it was shown at the correct place, after hiding them from menu, it was correctly hidden until now.
