### ISSUE TITLE
Add Mirakel DAVdroid source

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#57]
http://mirakel.azapps.de/releases.html

**Comment by DJaeger** [comment]
Think this is soon not needed anymore, as DAVdroid upstream will include the features of the fork in one of the next versions.
Let this open until it really happens.

**Comment by Bugsbane** [comment]
So has Davdroid included the needed vtodo integration from Mirakel yet? Just trying to figure out if I can use mainline Davdroid yet, or the clunky old 0.6.2 version from the Mirakel website

**Comment by JusticeRage** [comment]
I have no idea. I'll let @DJaeger comment on this, but otherwise I can add Mirakel to ApkTrack's sources and post a quick test APK while I'm working on a new major version.

**Comment by DJaeger** [comment]
The implementation is mainly integrated, but not activated for Mirakel.
This seems to will pend some more time...
@JusticeRage: Yes, please add it.

**Comment by JusticeRage** [comment]
I have posted a new [beta APK](kwiatkowski.fr/apktrack/ApkTrack_beta.apk)! (I haven't bumped the version for this minor update however). Let me know it this works for you.
Even though Mirakel and DAVdroid are listed on the same page, I had to create two separate update sources because I couldn't make a generic regular expression for both. I'll have to improve that in 2.0.

One thing worth noting is that the version number reported by DAVdroid does not match the one posted on their website (0.6.7_mirakel in the APK and 0.6.7-mirakel online) - this causes ApkTrack to report a version mismatch while there is none, but sadly there isn't much I can do about it.
Should we let them know about this?

**Comment by DJaeger** [comment]
As I think its not intended by them, it would be great, if you tell it to them.

**Comment by JusticeRage** [comment]
Here is a copy of the mail I just sent them:

---

Hi!

I am the maintainer of ApkTrack (http://apktrack.org/), a free app
which allows users to keep up with application updates without the
Play Store.

It works by scraping different websites in order to find out which
version of a given app is the latest. I've been asked by some users
(https://github.com/JusticeRage/ApkTrack/issues/57) use Mirakel's
official website (http://mirakel.azapps.de/releases.html) to track
Mirakel and DAVdroid updates, which I did this morning.

I have however noticed that the versions displayed on the website
differ from the actual one in the APK: for instance, the latest
version is 0.6.7_mirakel in the APK and 0.6.7-mirakel online (a dash
instead of an underscore).
This is very minor, but it makes my checks fail (since the latest
version and the actual versions differ). I can live with this, but I
just thought I'd let you know in case you want to want to fix it.

Thanks a lot!
Regards,
JusticeRage

**Comment by JusticeRage** [comment]
Mirakel doesn't seem interested in fixing this. Here's an excerpt from the maintainer's reply:
"You only need to search for mirakel-(.*).apk. The DAVdroid stuff is something else ;)".
