### ISSUE TITLE
App List Reload

### ISSUE THREAD

**Issue by yleyvag** [JusticeRage/ApkTrack#85]
When I update any application ApkTrack doesn't update that app in the applications list, so I have to delete ApkTrack data, like it was recently installed, because it stills showing the old version of any app.

**Comment by JusticeRage** [comment]
ApkTrack should be able to detect app updates automatically.
Are you using something like Greenify? It has surfaced that hibernating ApkTrack prevents it from receiving system notifications.

**Comment by yleyvag** [comment]
yes I'm using Greenify, I just remove it from Greenify, but why the app doesn't update the apps list everytime its open?

**Comment by JusticeRage** [comment]
Because that would cause the startup to be very slow. To do this, ApkTrack would have to list all the apps on the device (there may be more than 200), then check whether their version number is different from the one in the database. That's maybe 5 seconds before the app is reponsive, which is bad user experience.

A "refresh version" button is in the works to allow users to manually trigger a version re-detection, but I should probably display a warning message on ApkTrack's first launch if Greenify is detected on the device.

**Comment by yleyvag** [comment]
How ApkTrack detects that any app has been updated?

**Comment by JusticeRage** [comment]
Android posts Intents whenever an installation / uninstallation takes place, and ApkTrack registers with the system to receive them. But that doesn't happen when it is made to hibernate.

**Comment by yleyvag** [comment]
When I update my apps with Google Play Store app I don't see any Intents, ApkTrack detects when I update some app from Google Play Store?

**Comment by JusticeRage** [comment]
What do you mean, you don't "see" any intents? What code are you using to catch them?

**Comment by yleyvag** [comment]
I don't talk about any code. I'm talking of Google Play Store, for example, if I update Google Chrome from Google Play Store app, it downloads and install it, no one Intent is throw.

**Comment by JusticeRage** [comment]
Judging from your message, I'm not sure you know what an Intent is. That's a system message that is received by applications, so of course you're not going to see anything by looking at the screen. There is no popup involved.
